// <auto-generated />
namespace MediaManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Nome_Episodio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nome_Episodio));
        
        string IMigrationMetadata.Id
        {
            get { return "201511220607463_Nome_Episodio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
