//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Media Manager")]
        public string AppName {
            get {
                return ((string)(this["AppName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pref_PastaSeries {
            get {
                return ((string)(this["pref_PastaSeries"]));
            }
            set {
                this["pref_PastaSeries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pref_PastaFilmes {
            get {
                return ((string)(this["pref_PastaFilmes"]));
            }
            set {
                this["pref_PastaFilmes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pref_PastaAnimes {
            get {
                return ((string)(this["pref_PastaAnimes"]));
            }
            set {
                this["pref_PastaAnimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pref_PastaDownloads {
            get {
                return ((string)(this["pref_PastaDownloads"]));
            }
            set {
                this["pref_PastaDownloads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int pref_IntervaloDeProcuraConteudoNovo {
            get {
                return ((int)(this["pref_IntervaloDeProcuraConteudoNovo"]));
            }
            set {
                this["pref_IntervaloDeProcuraConteudoNovo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pref_FormatoSeries {
            get {
                return ((string)(this["pref_FormatoSeries"]));
            }
            set {
                this["pref_FormatoSeries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pref_FormatoFilmes {
            get {
                return ((string)(this["pref_FormatoFilmes"]));
            }
            set {
                this["pref_FormatoFilmes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pref_FormatoAnimes {
            get {
                return ((string)(this["pref_FormatoAnimes"]));
            }
            set {
                this["pref_FormatoAnimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string user_accessToken {
            get {
                return ((string)(this["user_accessToken"]));
            }
            set {
                this["user_accessToken"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bde862fb343e4249fff7af52459e5af3428d471e8bbd584db6355d2b1812aa60")]
        public string ClientID {
            get {
                return ((string)(this["ClientID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("79e450097ba69a929b696dab9c247534ecbc26112f00f687242dade1c9716f0b")]
        public string ClientSecret {
            get {
                return ((string)(this["ClientSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51038/TraktLogin.aspx")]
        public string CallbackUrl {
            get {
                return ((string)(this["CallbackUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api-v2launch.trakt.tv")]
        public string APIBaseUrl {
            get {
                return ((string)(this["APIBaseUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string user_username {
            get {
                return ((string)(this["user_username"]));
            }
            set {
                this["user_username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pt")]
        public string pref_IdiomaPesquisa {
            get {
                return ((string)(this["pref_IdiomaPesquisa"]));
            }
            set {
                this["pref_IdiomaPesquisa"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BD9B52E38797143A")]
        public string API_KeyTheTVDB {
            get {
                return ((string)(this["API_KeyTheTVDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2570d7bcbdfbc9af419035abdeef1452")]
        public string API_KeyFanartTv {
            get {
                return ((string)(this["API_KeyFanartTv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://thetvdb.com")]
        public string API_UrlTheTVDB {
            get {
                return ((string)(this["API_UrlTheTVDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://webservice.fanart.tv")]
        public string API_UrlFanartTv {
            get {
                return ((string)(this["API_UrlFanartTv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".webm|.mkv|.flv|.avi|.qt|.mov|.wmv|.yuv|.rm|.rmvb|.asf|.mp4|.m4p|.m4v|.mpg|.mp2|." +
            "mpeg|.mpe|.mpv|.m2v|.svi|.3gp|.3g2|.mxf|.roq|.nsv")]
        public string ExtensoesRenomeioPermitidas {
            get {
                return ((string)(this["ExtensoesRenomeioPermitidas"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime API_UltimaDataAtualizacaoTVDB {
            get {
                return ((global::System.DateTime)(this["API_UltimaDataAtualizacaoTVDB"]));
            }
            set {
                this["API_UltimaDataAtualizacaoTVDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pref_MetodoDeProcessamento {
            get {
                return ((int)(this["pref_MetodoDeProcessamento"]));
            }
            set {
                this["pref_MetodoDeProcessamento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pref_PastaBlackhole {
            get {
                return ((string)(this["pref_PastaBlackhole"]));
            }
            set {
                this["pref_PastaBlackhole"] = value;
            }
        }
    }
}
