//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaManager.Localizacao {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaManager.Localizacao.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  e .
        /// </summary>
        internal static string _e_ {
            get {
                return ResourceManager.GetString("_e_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicação iniciada com os seguintes argumentos: {0}.
        /// </summary>
        internal static string Aplicação_iniciada_com_os_seguintes_argumentos_0_ {
            get {
                return ResourceManager.GetString("Aplicação_iniciada_com_os_seguintes_argumentos_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busca personalizada....
        /// </summary>
        internal static string Busca_personalizada {
            get {
                return ResourceManager.GetString("Busca_personalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de preenchimento obrigatório..
        /// </summary>
        internal static string Campo_de_preenchimento_obrigatório {
            get {
                return ResourceManager.GetString("Campo_de_preenchimento_obrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando....
        /// </summary>
        internal static string Carregando {
            get {
                return ResourceManager.GetString("Carregando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando sinopse....
        /// </summary>
        internal static string Carregando_sinopse {
            get {
                return ResourceManager.GetString("Carregando_sinopse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código: &quot;{0}
        ///Arquivo: {1}.
        /// </summary>
        internal static string Codigo_0_Arquivo_1_ {
            get {
                return ResourceManager.GetString("Codigo_0_Arquivo_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episodio informado é de um tipo inválido..
        /// </summary>
        internal static string Episodio_informado_é_de_um_tipo_inválido {
            get {
                return ResourceManager.GetString("Episodio_informado_é_de_um_tipo_inválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo deve ser preenchido..
        /// </summary>
        internal static string Este_campo_deve_ser_preenchido {
            get {
                return ResourceManager.GetString("Este_campo_deve_ser_preenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemplo de título.
        /// </summary>
        internal static string Exemplo_de_título {
            get {
                return ResourceManager.GetString("Exemplo_de_título", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor preencher todos os campos antes de salvar..
        /// </summary>
        internal static string Favor_preencher_todos_os_campos_antes_de_salvar {
            get {
                return ResourceManager.GetString("Favor_preencher_todos_os_campos_antes_de_salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método de processamento não reconhecido ou inválido..
        /// </summary>
        internal static string Método_de_processamento_não_reconhecido_ou_inválido {
            get {
                return ResourceManager.GetString("Método_de_processamento_não_reconhecido_ou_inválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum resultado encontrado.
        /// </summary>
        internal static string Nenhum_resultado_encontrado {
            get {
                return ResourceManager.GetString("Nenhum_resultado_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum resultado encontrado, deseja pesquisar por outro nome?.
        /// </summary>
        internal static string Nenhum_resultado_encontrado__deseja_pesquisar_por_outro_nome {
            get {
                return ResourceManager.GetString("Nenhum_resultado_encontrado__deseja_pesquisar_por_outro_nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao abrir o feed &quot;{0}&quot; (URL: &quot;{1}&quot;)..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_abrir_o_feed_0_URL_1_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_abrir_o_feed_0_URL_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao adicionar {0}..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_adicionar_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_adicionar_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao adicionar {1} &quot;{0}&quot;.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_adicionar_1_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_adicionar_1_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao adicionar a qualidade &quot;{0}&quot;.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_adicionar_a_qualidade_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_adicionar_a_qualidade_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao adicionar episódios..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_adicionar_episódios {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_adicionar_episódios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao adicionar o conteúdo..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_adicionar_o_conteúdo {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_adicionar_o_conteúdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao adicionar o episódio com o ID {0}.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_adicionar_o_episódio_com_o_ID_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_adicionar_o_episódio_com_o_ID_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao adicionar o feed &quot;{0}&quot;.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_adicionar_o_feed_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_adicionar_o_feed_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao aplicar o algoritmo de correspondência no arquivo &quot;{0}&quot;.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_aplicar_o_algoritimo_de_correspondencia_no_arquivo_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_aplicar_o_algoritimo_de_correspondencia_no_arquivo_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao atualizar {0}..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_atualizar_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_atualizar_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao atualizar {1} &quot;{0}&quot;..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_atualizar_1_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_atualizar_1_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao atualizar a qualidade &quot;{0}&quot;.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_atualizar_a_qualidade_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_atualizar_a_qualidade_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao atualizar o conteúdo..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_atualizar_o_conteúdo {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_atualizar_o_conteúdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao atualizar o episódio de ID {0}.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_atualizar_o_episódio_de_ID_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_atualizar_o_episódio_de_ID_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao atualizar o feed &quot;{0}&quot;.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_atualizar_o_feed_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_atualizar_o_feed_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao atualizar os episódios .
        /// </summary>
        internal static string Ocorreu_um_erro_ao_atualizar_os_episódios {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_atualizar_os_episódios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao criar o {0}.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_criar_o__0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_criar_o__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao ordenar a lista utilizando o algoritmo de comparação..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_ordenar_a_lista_utilizando_o_algoritmo_de_comparação {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_ordenar_a_lista_utilizando_o_algoritmo_de_comparação", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao pesquisar {0}..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_pesquisar_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_pesquisar_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao pesquisar a qualidade de download de código &quot;{0}&quot;..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_pesquisar_a_qualidade_de_download_de_código_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_pesquisar_a_qualidade_de_download_de_código_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao pesquisar o feed de código &quot;{0}&quot;.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_pesquisar_o_feed_de_código_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_pesquisar_o_feed_de_código_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao pesquisar todos(as) os(as) {0}..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_pesquisar_todos_os_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_pesquisar_todos_os_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao procurar os episódios para baixar..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_procurar_os_episódios_para_baixar {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_procurar_os_episódios_para_baixar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao realizar o download..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_realizar_o_download {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_realizar_o_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao realizar o download das imagens..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_realizar_o_download_das_imagens {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_realizar_o_download_das_imagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao realizar o download do episódio &quot;{1}&quot; do RSS &quot;{0}&quot;.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_realizar_o_download_do_episódio_1_do_RSS_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_realizar_o_download_do_episódio_1_do_RSS_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao realizar o pós processamento..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_realizar_o_pós_processamento {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_realizar_o_pós_processamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao reconhecer o episódio .
        /// </summary>
        internal static string Ocorreu_um_erro_ao_reconhecer_o_episódio {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_reconhecer_o_episódio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao registrar a mensagem no log..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_registrar_a_mensagem_no_log {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_registrar_a_mensagem_no_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao remover {0}..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_remover_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_remover_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao remover {1} &quot;{0}&quot;.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_remover_1_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_remover_1_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao remover a qualidade &quot;{0}&quot;.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_remover_a_qualidade_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_remover_a_qualidade_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao remover o episódio &quot;{0}&quot;.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_remover_o_episódio_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_remover_o_episódio_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao remover o feed &quot;{0}&quot;.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_remover_o_feed_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_remover_o_feed_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao renomear os episódios dos argumentos na aplicação. Argumento: {0}.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_renomear_os_episódios_dos_argumentos_na_aplicação_Argumento_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_renomear_os_episódios_dos_argumentos_na_aplicação_Argumento_0_" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao retornar a lista de feeds..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_retornar_a_lista_de_feeds {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_retornar_a_lista_de_feeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao retornar a lista de qualidade de download..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_retornar_a_lista_de_qualidade_de_download {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_retornar_a_lista_de_qualidade_de_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao retornar o episódio &quot;{0}&quot; da temporada &quot;{1}&quot; do vídeo de ID &quot;{2}&quot;..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_retornar_o_episódio_0_da_temporada_1_do_vídeo_de_ID_2_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_retornar_o_episódio_0_da_temporada_1_do_vídeo_de_ID_2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao retornar o episódio com o código &quot;{0}&quot;.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_retornar_o_episódio_com_o_código_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_retornar_o_episódio_com_o_código_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao salvar os episódios de &quot;{0}&quot;.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_salvar_os_episódios_de_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_salvar_os_episódios_de_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao verificar os episódios no diretório &quot;{0}&quot;. Tipo do arquivo: &quot;{1}&quot;.
        /// </summary>
        internal static string Ocorreu_um_erro_ao_verificar_os_episódios_no_diretório_0__Tipo_1_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_verificar_os_episódios_no_diretório_0__Tipo_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao verificar se o episódio &quot;{0}&quot; ja foi renomeado..
        /// </summary>
        internal static string Ocorreu_um_erro_ao_verificar_se_o_episódio_ja_foi_renomeado_0_ {
            get {
                return ResourceManager.GetString("Ocorreu_um_erro_ao_verificar_se_o_episódio_ja_foi_renomeado_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os argumentos informados estão incorretos, favor verifica-los.
        ///Argumento: {0}.
        /// </summary>
        internal static string Os_argumentos_informados_estão_incorretos_favor_verifica_los_Argumento_0_ {
            get {
                return ResourceManager.GetString("Os_argumentos_informados_estão_incorretos_favor_verifica_los_Argumento_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para que o download possa ser realizado, preencha o campo &quot;Torrent blackhole&quot; nas preferências do programa..
        /// </summary>
        internal static string Para_que_o_download_possa_ser_realizado_preencha_o_campo_Torrent_blackhole_nas_preferências_do_programa {
            get {
                return ResourceManager.GetString("Para_que_o_download_possa_ser_realizado_preencha_o_campo_Torrent_blackhole_nas_pr" +
                        "eferências_do_programa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título do episódio.
        /// </summary>
        internal static string Título_do_episódio {
            get {
                return ResourceManager.GetString("Título_do_episódio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique mais detalhes no Log..
        /// </summary>
        internal static string Verifique_mais_detalhes_no_Log_ {
            get {
                return ResourceManager.GetString("Verifique_mais_detalhes_no_Log_", resourceCulture);
            }
        }
    }
}
